# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
                ('latitude', models.FloatField(default=28.600005)),
                ('longitude', models.FloatField(default=77.346965)),
            ],
        ),
    ]
